name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/cached-deps
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/cached-deps
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload Test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: "test-report"
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/cached-deps
      - name: Build website
        run: npm run build
      - name: Publish js file
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json

  # deploy:
  #   needs: [lint, test, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Output contents
  #       run: ls
  #     - name: Output filename
  #       run: echo "${{needs.build.outputs.script-file}}"
  #     - name: Deploy
  #       run: echo "Deploying..."
  deploy:
    needs: [lint, build]
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: dist-files
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Run custom action
        uses: ./.github/actions/deploy-s3-js
