name: Matrix workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        node-version: [18, 20, 22]
        operating-system: [ubuntu-24.04, ubuntu-22.04, macos-latest]
        include:
          - node-version: 20
            operating-system: windows-latest
        exclude:
          - node-version: 18
            operating-system: macos-latest
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Create build
        run: npm run build
