name: Reusable workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: false
        default: dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deployment done"
